use_frameworks!

platform :ios, '9.0'

target 'ZYFLogining_Example' do
  pod 'ZYFLogining', :path => '../'
  pod 'ZYFNetworking', :path => '../../ZYFNetworking'

  target 'ZYFLogining_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
